#############################################################################
# Makefile for building: QtCompass
# Generated by qmake (2.01a) (Qt 4.7.4) on: ?? ?? 25 22:06:04 2013
# Project:  QtSensorWeb.pro
# Template: app
# Command: d:/tempapp/develapp/qtsdk/madde/targets/harmattan_10.2011.34-1_rt1.2/bin/qmake.exe -spec d:/TempApp/DevelApp/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/default -unix CONFIG+=debug -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc -o Makefile QtSensorWeb.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -Id:/TempApp/DevelApp/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/default -I. -Id:/TempApp/DevelApp/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/include/qt4/QtCore -Id:/TempApp/DevelApp/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/include/qt4/QtNetwork -Id:/TempApp/DevelApp/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/include/qt4/QtGui -Id:/TempApp/DevelApp/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/include/qt4 -Id:/TempApp/DevelApp/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/include/qt4/QtSensors -Id:/TempApp/DevelApp/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/include/qt4 -Id:/TempApp/DevelApp/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/include/qt4/QtMobility -Imoc
LINK          = g++
LFLAGS        = -Wl,-rpath,G:/usr/lib
LIBS          = $(SUBLIBS)  -LD:/TempApp/DevelApp/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib -L/usr/lib -lQtSensors -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = d:/tempapp/develapp/qtsdk/madde/targets/harmattan_10.2011.34-1_rt1.2/bin/qmake.exe
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = main.cpp \
		compass.cpp \
		mainwindow.cpp \
		webclient.cpp moc/moc_compass.cpp \
		moc/moc_mainwindow.cpp \
		moc/moc_webclient.cpp \
		rcc/qrc_Qtcompass.cpp
OBJECTS       = obj/main.o \
		obj/compass.o \
		obj/mainwindow.o \
		obj/webclient.o \
		obj/moc_compass.o \
		obj/moc_mainwindow.o \
		obj/moc_webclient.o \
		obj/qrc_Qtcompass.o
DIST          = d:/TempApp/DevelApp/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/g++.conf \
		d:/TempApp/DevelApp/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/unix.conf \
		d:/TempApp/DevelApp/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/linux.conf \
		d:/TempApp/DevelApp/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/qconfig.pri \
		d:/TempApp/DevelApp/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt_functions.prf \
		d:/TempApp/DevelApp/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt_config.prf \
		d:/TempApp/DevelApp/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		d:/TempApp/DevelApp/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/default_pre.prf \
		d:/TempApp/DevelApp/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/debug.prf \
		d:/TempApp/DevelApp/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/default_post.prf \
		d:/TempApp/DevelApp/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/mobility.prf \
		d:/TempApp/DevelApp/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/warn_on.prf \
		d:/TempApp/DevelApp/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt.prf \
		d:/TempApp/DevelApp/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/unix/thread.prf \
		d:/TempApp/DevelApp/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/moc.prf \
		d:/TempApp/DevelApp/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/resources.prf \
		d:/TempApp/DevelApp/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/uic.prf \
		d:/TempApp/DevelApp/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/yacc.prf \
		d:/TempApp/DevelApp/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/lex.prf \
		QtSensorWeb.pro
QMAKE_TARGET  = QtCompass
DESTDIR       = 
TARGET        = QtCompass

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: QtSensorWeb.pro  d:/TempApp/DevelApp/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/default/qmake.conf d:/TempApp/DevelApp/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/g++.conf \
		d:/TempApp/DevelApp/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/unix.conf \
		d:/TempApp/DevelApp/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/linux.conf \
		d:/TempApp/DevelApp/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/qconfig.pri \
		d:/TempApp/DevelApp/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt_functions.prf \
		d:/TempApp/DevelApp/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt_config.prf \
		d:/TempApp/DevelApp/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		d:/TempApp/DevelApp/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/default_pre.prf \
		d:/TempApp/DevelApp/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/debug.prf \
		d:/TempApp/DevelApp/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/default_post.prf \
		d:/TempApp/DevelApp/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/mobility.prf \
		d:/TempApp/DevelApp/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/warn_on.prf \
		d:/TempApp/DevelApp/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt.prf \
		d:/TempApp/DevelApp/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/unix/thread.prf \
		d:/TempApp/DevelApp/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/moc.prf \
		d:/TempApp/DevelApp/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/resources.prf \
		d:/TempApp/DevelApp/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/uic.prf \
		d:/TempApp/DevelApp/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/yacc.prf \
		d:/TempApp/DevelApp/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/lex.prf \
		d:/TempApp/DevelApp/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtGui.prl \
		d:/TempApp/DevelApp/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtNetwork.prl \
		d:/TempApp/DevelApp/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtCore.prl
	$(QMAKE) -spec d:/TempApp/DevelApp/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/default -unix CONFIG+=debug -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc -o Makefile QtSensorWeb.pro
d:/TempApp/DevelApp/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/g++.conf:
d:/TempApp/DevelApp/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/unix.conf:
d:/TempApp/DevelApp/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/linux.conf:
d:/TempApp/DevelApp/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/qconfig.pri:
d:/TempApp/DevelApp/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt_functions.prf:
d:/TempApp/DevelApp/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt_config.prf:
d:/TempApp/DevelApp/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
d:/TempApp/DevelApp/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/default_pre.prf:
d:/TempApp/DevelApp/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/debug.prf:
d:/TempApp/DevelApp/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/default_post.prf:
d:/TempApp/DevelApp/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/mobility.prf:
d:/TempApp/DevelApp/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/warn_on.prf:
d:/TempApp/DevelApp/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt.prf:
d:/TempApp/DevelApp/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/unix/thread.prf:
d:/TempApp/DevelApp/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/moc.prf:
d:/TempApp/DevelApp/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/resources.prf:
d:/TempApp/DevelApp/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/uic.prf:
d:/TempApp/DevelApp/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/yacc.prf:
d:/TempApp/DevelApp/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/lex.prf:
d:/TempApp/DevelApp/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtGui.prl:
d:/TempApp/DevelApp/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtNetwork.prl:
d:/TempApp/DevelApp/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec d:/TempApp/DevelApp/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/default -unix CONFIG+=debug -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc -o Makefile QtSensorWeb.pro

dist: 
	@$(CHK_DIR_EXISTS) obj/QtCompass1.0.0 || $(MKDIR) obj/QtCompass1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) obj/QtCompass1.0.0/ && $(COPY_FILE) --parents compass.h mainwindow.h webclient.h obj/QtCompass1.0.0/ && $(COPY_FILE) --parents Qtcompass.qrc obj/QtCompass1.0.0/ && $(COPY_FILE) --parents main.cpp compass.cpp mainwindow.cpp webclient.cpp obj/QtCompass1.0.0/ && (cd `dirname obj/QtCompass1.0.0` && $(TAR) QtCompass1.0.0.tar QtCompass1.0.0 && $(COMPRESS) QtCompass1.0.0.tar) && $(MOVE) `dirname obj/QtCompass1.0.0`/QtCompass1.0.0.tar.gz . && $(DEL_FILE) -r obj/QtCompass1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc/moc_compass.cpp moc/moc_mainwindow.cpp moc/moc_webclient.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc/moc_compass.cpp moc/moc_mainwindow.cpp moc/moc_webclient.cpp
moc/moc_compass.cpp: webclient.h \
		compass.h
	D:/TempApp/DevelApp/QtSDK/Madde/targets/harmattan_10.2011.34-1_rt1.2/bin/moc.exe $(DEFINES) $(INCPATH) compass.h -o moc/moc_compass.cpp

moc/moc_mainwindow.cpp: compass.h \
		webclient.h \
		mainwindow.h
	D:/TempApp/DevelApp/QtSDK/Madde/targets/harmattan_10.2011.34-1_rt1.2/bin/moc.exe $(DEFINES) $(INCPATH) mainwindow.h -o moc/moc_mainwindow.cpp

moc/moc_webclient.cpp: webclient.h
	D:/TempApp/DevelApp/QtSDK/Madde/targets/harmattan_10.2011.34-1_rt1.2/bin/moc.exe $(DEFINES) $(INCPATH) webclient.h -o moc/moc_webclient.cpp

compiler_rcc_make_all: rcc/qrc_Qtcompass.cpp
compiler_rcc_clean:
	-$(DEL_FILE) rcc/qrc_Qtcompass.cpp
rcc/qrc_Qtcompass.cpp: Qtcompass.qrc \
		images/bg.jpg \
		images/compass.png
	d:/TempApp/DevelApp/QtSDK/Madde/targets/harmattan_10.2011.34-1_rt1.2/bin/rcc.exe -name Qtcompass Qtcompass.qrc -o rcc/qrc_Qtcompass.cpp

compiler_image_collection_make_all: ui/qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) ui/qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

obj/main.o: main.cpp mainwindow.h \
		compass.h \
		webclient.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/main.o main.cpp

obj/compass.o: compass.cpp compass.h \
		webclient.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/compass.o compass.cpp

obj/mainwindow.o: mainwindow.cpp mainwindow.h \
		compass.h \
		webclient.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/mainwindow.o mainwindow.cpp

obj/webclient.o: webclient.cpp webclient.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/webclient.o webclient.cpp

obj/moc_compass.o: moc/moc_compass.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_compass.o moc/moc_compass.cpp

obj/moc_mainwindow.o: moc/moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_mainwindow.o moc/moc_mainwindow.cpp

obj/moc_webclient.o: moc/moc_webclient.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_webclient.o moc/moc_webclient.cpp

obj/qrc_Qtcompass.o: rcc/qrc_Qtcompass.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/qrc_Qtcompass.o rcc/qrc_Qtcompass.cpp

####### Install

install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/opt/QtCompass/bin/ || $(MKDIR) $(INSTALL_ROOT)/opt/QtCompass/bin/ 
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/opt/QtCompass/bin/$(QMAKE_TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/opt/QtCompass/bin/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/QtCompass/bin/ 


install:  install_target  FORCE

uninstall: uninstall_target   FORCE

FORCE:

